#!/bin/bash

set -e

git init --quiet --initial-branch=trunk
git config commit.gpgSign false
rm -rf .git/hooks/*
git config --local user.email "daisy@example.com"
git config --local user.name "Daisy Developer"
git commit --quiet -m "Initial commit" --allow-empty
