#!/bin/bash

set -e

git init --quiet .
git config commit.gpgSign false
rm -rf .git/hooks/*
git config user.email "daisy@example.com"
git config user.name "Daisy Developer"
git commit --quiet -m "Initial commit" --allow-empty
